// ─── Programmatic SEO Variant Data ───────────────────────────────────────────
// Each variant creates a unique /compress/[slug] page targeting a long-tail keyword.

export type SeoVariant = {
  slug: string;
  h1: string;
  h1Short: string; // shorter version for pills/links
  title: string; // <title> tag
  description: string; // meta description
  keywords: string[];
  category: string;
  intro: string; // 2-3 sentence intro paragraph
  tip: string; // contextual tip for this use case
  faqs: Array<{ q: string; a: string }>;
};

// ── Categories ───────────────────────────────────────────────────────────────
const categories = {
  email: "Email & Sharing",
  size: "Target File Size",
  document: "Document Type",
  platform: "Platform & Device",
  industry: "Industry & Use Case",
  quality: "Quality & Settings",
  batch: "Batch & Bulk",
  general: "General",
} as const;

// ── Helper to build a variant with defaults ──────────────────────────────────
function v(
  slug: string,
  h1: string,
  h1Short: string,
  title: string,
  description: string,
  keywords: string[],
  category: string,
  intro: string,
  tip: string,
  faqs: Array<{ q: string; a: string }>,
): SeoVariant {
  return { slug, h1, h1Short, title, description, keywords, category, intro, tip, faqs };
}

export const seoVariants: SeoVariant[] = [
  // ── EMAIL & SHARING (25) ─────────────────────────────────────────────────
  v("compress-pdf-for-email", "Compress PDF for Email", "PDF for Email",
    "Compress PDF for Email — Reduce Size to Send as Attachment",
    "Shrink PDF files to fit email attachment limits. Free online PDF compressor — no signup, no upload to server.",
    ["compress pdf for email", "reduce pdf for email attachment", "email pdf compressor", "shrink pdf to email"],
    categories.email,
    "Most email services limit attachments to 10–25 MB. PDF Minify compresses your documents so they fit within these limits while keeping the content readable.",
    "For Gmail's 25 MB limit, aim for the left side of the compression slider to get maximum reduction.",
    [{ q: "What is the email attachment limit?", a: "Gmail and Outlook allow up to 25 MB. Yahoo allows 25 MB. For larger files, use cloud links." }, { q: "Will the text still be readable?", a: "Yes. PDF Minify optimizes images within the PDF while preserving text clarity." }]),

  v("compress-pdf-for-gmail", "Compress PDF for Gmail", "PDF for Gmail",
    "Compress PDF for Gmail — Fit Under 25 MB Limit",
    "Reduce PDF file size to send via Gmail. Free browser-based compressor, no upload required.",
    ["compress pdf for gmail", "gmail pdf attachment size", "reduce pdf gmail", "shrink pdf gmail 25mb"],
    categories.email,
    "Gmail limits attachments to 25 MB. If your PDF exceeds this limit, PDF Minify can reduce its size by up to 80% — entirely in your browser.",
    "If your PDF has many high-resolution images, you can achieve significant savings. Text-heavy PDFs may already be small.",
    [{ q: "What is Gmail's attachment limit?", a: "Gmail allows up to 25 MB per attachment. Larger files are automatically uploaded to Google Drive." }, { q: "Can I compress multiple PDFs for Gmail?", a: "Yes. Drop up to 20 files and download them all as a ZIP." }]),

  v("compress-pdf-for-outlook", "Compress PDF for Outlook", "PDF for Outlook",
    "Compress PDF for Outlook — Reduce Size for Email Attachment",
    "Shrink PDF files to fit Outlook's 20 MB attachment limit. Free, private, browser-based compression.",
    ["compress pdf for outlook", "outlook pdf attachment limit", "reduce pdf outlook", "shrink pdf outlook"],
    categories.email,
    "Microsoft Outlook limits attachments to 20 MB (or less, depending on your organization's settings). Use PDF Minify to reduce your files.",
    "Corporate Outlook accounts may have even smaller limits (5–10 MB). Check with your IT department.",
    [{ q: "What is Outlook's attachment limit?", a: "Default Outlook limit is 20 MB, but corporate accounts may have smaller limits." }, { q: "Does compression affect PDF signatures?", a: "Compression re-renders pages as images, so digital signatures may not be preserved." }]),

  v("compress-pdf-for-whatsapp", "Compress PDF for WhatsApp", "PDF for WhatsApp",
    "Compress PDF for WhatsApp — Fit Under 100 MB Limit",
    "Reduce PDF size to share on WhatsApp. Free online compressor, works in your browser.",
    ["compress pdf for whatsapp", "whatsapp pdf size limit", "send large pdf whatsapp", "reduce pdf whatsapp"],
    categories.email,
    "WhatsApp allows document sharing up to 100 MB, but smaller files send faster and use less data. Compress your PDFs for quicker sharing.",
    "Smaller PDFs load faster on mobile devices — aim for under 5 MB for the best WhatsApp experience.",
    [{ q: "What is WhatsApp's file size limit?", a: "WhatsApp allows documents up to 100 MB, but smaller files transfer faster." }, { q: "Will recipients see quality loss?", a: "For most documents, the quality difference is minimal, especially on mobile screens." }]),

  v("compress-pdf-for-slack", "Compress PDF for Slack", "PDF for Slack",
    "Compress PDF for Slack — Reduce File Size for Sharing",
    "Shrink PDFs to share on Slack within file upload limits. Free, no signup.",
    ["compress pdf for slack", "slack pdf upload limit", "reduce pdf slack", "shrink pdf for slack"],
    categories.email,
    "Slack's free tier limits file storage. Compressing PDFs helps you stay within limits and ensures faster loading for your team.",
    "Slack free tier has limited storage per workspace. Smaller PDFs help you stay under the limit longer.",
    [{ q: "What is Slack's file upload limit?", a: "Slack allows files up to 1 GB for paid plans, but storage is limited on free plans." }, { q: "Can I share compressed PDFs in channels?", a: "Yes. Compressed PDFs work just like regular PDFs in Slack." }]),

  v("compress-pdf-to-share-online", "Compress PDF to Share Online", "Share Online",
    "Compress PDF to Share Online — Faster Downloads",
    "Reduce PDF file size for faster online sharing. Free browser-based compressor.",
    ["compress pdf to share online", "reduce pdf for sharing", "smaller pdf for download", "compress pdf link"],
    categories.email,
    "Sharing large PDFs online means slow downloads for recipients. PDF Minify makes your files smaller for faster, smoother sharing.",
    "If sharing via a link, a smaller file means people can view it faster, especially on mobile networks.",
    [{ q: "How much smaller will my PDF be?", a: "Typical savings range from 30–80%, depending on content." }, { q: "Is the link shareable after compression?", a: "You download the compressed file. Upload it to your preferred sharing service." }]),

  v("compress-pdf-for-upload", "Compress PDF for Upload", "PDF for Upload",
    "Compress PDF for Upload — Reduce File Size for Web Forms",
    "Shrink PDF documents to meet upload size limits on websites and portals.",
    ["compress pdf for upload", "reduce pdf for web upload", "shrink pdf upload form", "pdf too large to upload"],
    categories.email,
    "Many websites, job portals, and government forms have strict upload limits (1–10 MB). Compress your PDF to fit.",
    "Check the exact size limit before compressing. Adjust the slider until the output is under the required size.",
    [{ q: "How do I know the required file size?", a: "The upload form usually shows the limit (e.g., 'Max 5 MB'). Compress accordingly." }, { q: "Can I compress multiple times?", a: "Yes, but each pass may reduce quality. Try to achieve the target in one compression." }]),

  v("compress-pdf-for-website", "Compress PDF for Website", "PDF for Website",
    "Compress PDF for Website — Optimize PDFs for Web Download",
    "Reduce PDF size for faster website downloads. Improve page speed and user experience.",
    ["compress pdf for website", "optimize pdf web", "pdf web download fast", "reduce pdf website hosting"],
    categories.email,
    "Large PDFs on your website slow down downloads and hurt user experience. Compress them to reduce bandwidth and improve load times.",
    "After compression, upload the smaller PDF to your CMS. Your visitors will appreciate faster downloads.",
    [{ q: "Does smaller PDF improve SEO?", a: "Indirectly — faster page speeds improve Core Web Vitals, which can improve rankings." }, { q: "Should I compress all my website PDFs?", a: "Yes. There's no downside to offering smaller, faster-loading PDFs to your visitors." }]),

  v("compress-pdf-for-google-drive", "Compress PDF for Google Drive", "PDF for Drive",
    "Compress PDF for Google Drive — Save Storage Space",
    "Reduce PDF file sizes to save Google Drive storage. Free, private compression in your browser.",
    ["compress pdf google drive", "reduce pdf drive storage", "shrink pdf for google drive", "save google drive space pdf"],
    categories.email,
    "Google Drive gives you 15 GB of free storage. Compressing PDFs before uploading helps you use that space more efficiently.",
    "Compress large scan-based PDFs first — they often have the biggest size reduction potential.",
    [{ q: "How much Drive space can I save?", a: "If your PDFs reduce by 60%, a folder of 100 MB PDFs would drop to about 40 MB." }, { q: "Will compressed PDFs still be searchable in Drive?", a: "Compression converts pages to images. Text search may be reduced for image-heavy PDFs." }]),

  v("compress-pdf-for-dropbox", "Compress PDF for Dropbox", "PDF for Dropbox",
    "Compress PDF for Dropbox — Reduce Storage Usage",
    "Shrink PDF files before uploading to Dropbox. Save storage and bandwidth.",
    ["compress pdf dropbox", "reduce pdf for dropbox", "shrink pdf dropbox upload", "save dropbox space"],
    categories.email,
    "Dropbox Basic offers 2 GB of free storage. Every MB counts. Compress your PDFs to store more files.",
    "Dropbox Basic is limited. Prioritize compressing large reports and presentations to maximize your free space.",
    [{ q: "How much Dropbox space will I save?", a: "Depends on your PDFs, but 30–80% reduction is typical for image-heavy documents." }, { q: "Will shared links still work?", a: "Yes. Upload the compressed PDF and share the link as usual." }]),

  v("compress-pdf-for-discord", "Compress PDF for Discord", "PDF for Discord",
    "Compress PDF for Discord — Fit Under Upload Limit",
    "Reduce PDF size to share on Discord. Free tier limits to 25 MB.",
    ["compress pdf for discord", "discord pdf upload limit", "reduce pdf discord", "shrink pdf discord"],
    categories.email,
    "Discord free accounts limit file uploads to 25 MB (50 MB with Nitro). Compress your PDFs to share them in servers and DMs.",
    "Discord Nitro increases the limit to 50 MB and Nitro Basic to 50 MB as well.",
    [{ q: "What is Discord's file size limit?", a: "Free: 25 MB, Nitro Basic: 50 MB, Nitro: 500 MB." }, { q: "Can I send compressed PDFs in DMs?", a: "Yes, compressed PDFs work normally in both DMs and server channels." }]),

  v("compress-pdf-for-linkedin", "Compress PDF for LinkedIn", "PDF for LinkedIn",
    "Compress PDF for LinkedIn — Share Smaller Documents",
    "Reduce PDF size for LinkedIn document posts and messages. Free online compressor.",
    ["compress pdf for linkedin", "linkedin pdf upload", "reduce pdf linkedin post", "shrink pdf linkedin"],
    categories.email,
    "LinkedIn supports PDF document posts (up to 300 MB) but smaller files load faster for your audience. Messages have a 200 MB limit.",
    "LinkedIn carousel posts use PDFs — compress yours for faster loading across mobile feeds.",
    [{ q: "Can I post PDFs on LinkedIn?", a: "Yes. LinkedIn supports document posts in PDF format up to 300 MB." }, { q: "Does compression affect carousel quality?", a: "Minimal impact. Most viewers won't notice on mobile screens." }]),

  // ── TARGET FILE SIZE (20) ────────────────────────────────────────────────
  v("compress-pdf-under-1mb", "Compress PDF Under 1 MB", "Under 1 MB",
    "Compress PDF Under 1 MB — Reduce to Less Than 1 MB",
    "Shrink PDF files to under 1 MB. Free online compressor for tight file size requirements.",
    ["compress pdf under 1mb", "reduce pdf to 1mb", "pdf under 1 mb", "shrink pdf 1mb"],
    categories.size,
    "Some upload forms and systems require files under 1 MB. Use aggressive compression settings to reach this target.",
    "Move the compression slider all the way to the left for maximum reduction. Check the output size — if still over 1 MB, the PDF may have too many pages.",
    [{ q: "Can all PDFs be compressed under 1 MB?", a: "Not always. Very long documents or high-resolution scans may not reach 1 MB even at maximum compression." }, { q: "What settings should I use?", a: "Move the slider fully left for the smallest possible output." }]),

  v("compress-pdf-under-2mb", "Compress PDF Under 2 MB", "Under 2 MB",
    "Compress PDF Under 2 MB — Fit Within 2 MB Limit",
    "Reduce PDF file size to under 2 MB for upload requirements. Free, instant, browser-based.",
    ["compress pdf under 2mb", "reduce pdf to 2mb", "pdf under 2 mb", "shrink pdf 2mb limit"],
    categories.size,
    "Many government portals and job applications require PDFs under 2 MB. PDF Minify helps you meet this requirement.",
    "A 10-page document with images typically compresses well to under 2 MB.",
    [{ q: "What types of PDFs compress to under 2 MB?", a: "Most single-digit page PDFs with moderate images can reach under 2 MB." }, { q: "What if my PDF is still over 2 MB?", a: "Try maximum compression or split the document into smaller parts." }]),

  v("compress-pdf-under-5mb", "Compress PDF Under 5 MB", "Under 5 MB",
    "Compress PDF Under 5 MB — Reduce to 5 MB or Less",
    "Shrink PDF files to under 5 MB for email and upload limits. Free online compressor.",
    ["compress pdf under 5mb", "reduce pdf to 5mb", "pdf under 5 mb", "compress pdf 5mb limit"],
    categories.size,
    "5 MB is a common limit for many email systems and form uploads. PDF Minify can typically reach this target for documents up to 50 pages.",
    "At medium compression, most presentations and reports fit comfortably under 5 MB.",
    [{ q: "Is 5 MB enough for a presentation?", a: "Yes. Most compressed presentations with images fit under 5 MB." }, { q: "What about very long documents?", a: "Documents over 100 pages may need more aggressive compression to reach 5 MB." }]),

  v("compress-pdf-under-10mb", "Compress PDF Under 10 MB", "Under 10 MB",
    "Compress PDF Under 10 MB — Reduce for Upload Limits",
    "Reduce PDF to under 10 MB for email attachments and web uploads. Free instant compression.",
    ["compress pdf under 10mb", "reduce pdf to 10mb", "pdf under 10 mb", "compress pdf 10mb"],
    categories.size,
    "10 MB is a common threshold for many systems. Most PDFs can be compressed to fit within this limit.",
    "Even large presentations (50+ slides) usually compress to under 10 MB at medium quality.",
    [{ q: "Can I compress a 100 MB PDF to under 10 MB?", a: "Possibly. It depends on content — image-heavy PDFs have more room for compression." }, { q: "Will the file still be printable?", a: "Yes. Compressed PDFs print well at standard resolutions." }]),

  v("compress-pdf-under-25mb", "Compress PDF Under 25 MB", "Under 25 MB",
    "Compress PDF Under 25 MB — Fit Within Email Limits",
    "Reduce PDF to under 25 MB for Gmail and other email services. Free online tool.",
    ["compress pdf under 25mb", "reduce pdf to 25mb", "pdf under 25 mb", "email attachment 25mb"],
    categories.size,
    "25 MB is the attachment limit for Gmail and most email services. PDF Minify helps large documents fit.",
    "If your PDF is 30–50 MB, medium compression usually brings it under 25 MB.",
    [{ q: "What email services have a 25 MB limit?", a: "Gmail, Yahoo, and many corporate email systems cap at 25 MB per attachment." }, { q: "What if my PDF is over 50 MB?", a: "PDF Minify accepts files up to 50 MB. Use maximum compression for the best result." }]),

  v("compress-pdf-to-100kb", "Compress PDF to 100 KB", "Under 100 KB",
    "Compress PDF to 100 KB — Extreme Compression",
    "Reduce PDF file size to around 100 KB for strict size limits. Maximum compression mode.",
    ["compress pdf to 100kb", "reduce pdf 100kb", "pdf under 100kb", "extreme pdf compression"],
    categories.size,
    "Some systems require extremely small files. Reaching 100 KB is possible for simple, short PDFs with minimal images.",
    "For 100 KB targets, use maximum compression and expect some quality reduction on images.",
    [{ q: "Can any PDF reach 100 KB?", a: "Only simple PDFs (1–3 pages, mostly text) can reliably reach 100 KB." }, { q: "Will the text be legible?", a: "Text remains readable but images will be lower quality at extreme compression." }]),

  v("compress-pdf-to-200kb", "Compress PDF to 200 KB", "Under 200 KB",
    "Compress PDF to 200 KB — Strong Compression for Small Files",
    "Shrink PDF to approximately 200 KB. Ideal for online forms with strict limits.",
    ["compress pdf to 200kb", "reduce pdf 200kb", "pdf under 200kb", "small pdf file"],
    categories.size,
    "200 KB is a target for some government forms and online application portals. Short documents with moderate images can reach this size.",
    "Keep documents to 5 pages or fewer for the best chance of reaching 200 KB.",
    [{ q: "How many pages can fit in 200 KB?", a: "Typically 1–5 pages depending on image content." }, { q: "What about scanned documents?", a: "Scanned PDFs may struggle to reach 200 KB even at maximum compression." }]),

  v("compress-pdf-to-500kb", "Compress PDF to 500 KB", "Under 500 KB",
    "Compress PDF to 500 KB — Reduce to Half a Megabyte",
    "Compress PDF files to approximately 500 KB. Perfect for online applications and forms.",
    ["compress pdf to 500kb", "reduce pdf 500kb", "pdf under 500kb", "compress pdf half mb"],
    categories.size,
    "500 KB is a common requirement for online job applications and government submissions. Most short documents can reach this target.",
    "Documents up to 10 pages with moderate images typically compress to around 500 KB.",
    [{ q: "Is 500 KB enough for a resume?", a: "Yes. Most resumes are 1–3 pages and compress well under 500 KB." }, { q: "What about multi-page reports?", a: "Reports under 15 pages usually fit within 500 KB at medium compression." }]),

  v("compress-pdf-by-50-percent", "Compress PDF by 50%", "Reduce by 50%",
    "Compress PDF by 50% — Halve Your File Size",
    "Reduce PDF file size by approximately 50%. Balanced compression for everyday use.",
    ["compress pdf by 50 percent", "reduce pdf half size", "halve pdf size", "50 percent pdf compression"],
    categories.size,
    "A 50% reduction is a sweet spot for most documents — significantly smaller without noticeable quality loss.",
    "Set the compression slider to the middle position for approximately 50% reduction.",
    [{ q: "What compression setting gives 50%?", a: "The default middle position typically achieves 40–60% reduction." }, { q: "Is 50% reduction always possible?", a: "For image-heavy PDFs, yes. Text-only PDFs may already be near their minimum size." }]),

  v("compress-pdf-by-80-percent", "Compress PDF by 80%", "Reduce by 80%",
    "Compress PDF by 80% — Maximum Size Reduction",
    "Achieve up to 80% file size reduction on PDF documents. Aggressive but effective compression.",
    ["compress pdf by 80 percent", "maximum pdf compression", "reduce pdf 80 percent", "aggressive pdf compression"],
    categories.size,
    "80% reduction is achievable for PDFs with lots of images, scans, and screenshots. Text quality is preserved but image resolution is lowered.",
    "Move the slider to the far left for maximum compression. Ideal for archiving or sharing, not for printing.",
    [{ q: "When should I use 80% compression?", a: "When you need the smallest possible file — for archiving, emailing, or limited storage." }, { q: "Will the PDF still be readable?", a: "Yes, text remains clear. Images will be lower resolution but still viewable." }]),

  // ── DOCUMENT TYPE (30) ───────────────────────────────────────────────────
  v("compress-scanned-pdf", "Compress Scanned PDF", "Scanned PDFs",
    "Compress Scanned PDF — Reduce Scan File Size",
    "Shrink scanned PDF documents. Scans contain large images that compress well. Free tool.",
    ["compress scanned pdf", "reduce scanned document size", "shrink scan pdf", "scanned pdf compressor"],
    categories.document,
    "Scanned PDFs are essentially images wrapped in a PDF container. They often have enormous file sizes — perfect candidates for compression.",
    "Scanned documents usually compress by 50–80% because they contain full-page images at high resolution.",
    [{ q: "Why are scanned PDFs so large?", a: "Each page is a full image (often 300 DPI), which makes even a 5-page scan 20+ MB." }, { q: "Will text in scans remain readable?", a: "Yes, at most compression levels. Only extreme compression may affect readability." }]),

  v("compress-pdf-resume", "Compress PDF Resume", "Resume / CV",
    "Compress PDF Resume — Reduce CV File Size",
    "Shrink your PDF resume to meet job application upload limits. Free, private compressor.",
    ["compress pdf resume", "reduce resume file size", "shrink cv pdf", "resume pdf compressor"],
    categories.document,
    "Job portals often limit resume uploads to 1–5 MB. If your PDF resume has images, logos, or charts, compression helps fit the limit.",
    "Most resumes (1–3 pages) compress to under 500 KB even at moderate compression settings.",
    [{ q: "What size should a resume PDF be?", a: "Under 1 MB is ideal. Most ATS systems and portals accept up to 5 MB." }, { q: "Will formatting be preserved?", a: "PDF Minify preserves the visual layout of your resume." }]),

  v("compress-pdf-presentation", "Compress PDF Presentation", "Presentations",
    "Compress PDF Presentation — Reduce Slide File Size",
    "Shrink PDF presentations with images and charts. Ideal for sharing via email or chat.",
    ["compress pdf presentation", "reduce presentation pdf", "shrink slides pdf", "presentation pdf compressor"],
    categories.document,
    "PDF presentations converted from PowerPoint often have large embedded images. Compression can reduce them from 50 MB to under 10 MB.",
    "Presentations with full-page images benefit most from compression. Text-heavy slides are already small.",
    [{ q: "Can I compress a 100-slide presentation?", a: "Yes. PDF Minify handles large documents. Expect significant savings for image-heavy slides." }, { q: "Will charts and graphs stay clear?", a: "Yes. At moderate compression, charts and text remain sharp." }]),

  v("compress-pdf-ebook", "Compress PDF eBook", "eBooks",
    "Compress PDF eBook — Reduce Digital Book File Size",
    "Shrink PDF eBooks for easier storage and sharing. Free online compression.",
    ["compress pdf ebook", "reduce ebook file size", "shrink ebook pdf", "compress digital book"],
    categories.document,
    "PDF eBooks with illustrations, photos, and cover art can be very large. Compress them for faster downloads and smaller storage footprint.",
    "eBooks with many photos (photography books, magazines) benefit most. Text novels are usually already small.",
    [{ q: "Will the cover image still look good?", a: "At moderate compression, cover images remain presentable. Extreme compression may reduce sharpness." }, { q: "Can I compress textbook PDFs?", a: "Yes. Textbooks with diagrams and images compress well." }]),

  v("compress-pdf-invoice", "Compress PDF Invoice", "Invoices",
    "Compress PDF Invoice — Reduce for Email & Storage",
    "Shrink PDF invoices for email attachments and cloud storage. Free, private tool.",
    ["compress pdf invoice", "reduce invoice size", "shrink invoice pdf", "invoice pdf compressor"],
    categories.document,
    "Invoices are typically small, but if they contain logos, product images, or stamps, compression can help reduce file size.",
    "Invoices with embedded logos and images typically compress by 30–50%.",
    [{ q: "Are invoices too small to compress?", a: "Many are already under 1 MB, but those with images or scanned elements can benefit." }, { q: "Will the invoice still be legally valid?", a: "The visual content is preserved. For legal purposes, check your jurisdiction's requirements." }]),

  v("compress-pdf-contract", "Compress PDF Contract", "Contracts",
    "Compress PDF Contract — Reduce Legal Document Size",
    "Shrink PDF contracts and legal documents for email and storage. Free compression.",
    ["compress pdf contract", "reduce contract size", "shrink legal pdf", "contract pdf compressor"],
    categories.document,
    "Legal contracts can be large, especially when they include signed pages, stamps, and appendices. Compression makes sharing easier.",
    "Contracts with scanned signature pages benefit most from compression.",
    [{ q: "Will signatures be preserved?", a: "Visual signatures (images) are preserved. Digital/cryptographic signatures may be affected." }, { q: "Is compressed contract legally binding?", a: "The content is preserved. Consult a legal professional for your jurisdiction's requirements." }]),

  v("compress-pdf-report", "Compress PDF Report", "Reports",
    "Compress PDF Report — Reduce Business Report Size",
    "Shrink PDF business reports with charts and images. Free online compressor.",
    ["compress pdf report", "reduce report size", "shrink business report pdf", "compress annual report"],
    categories.document,
    "Business reports with charts, graphs, and embedded images are prime candidates for compression. Share them faster via email.",
    "Annual reports and financial statements with charts often compress by 40–70%.",
    [{ q: "Can I compress multi-chapter reports?", a: "Yes. PDF Minify handles large documents with many pages." }, { q: "Will charts remain legible?", a: "At moderate compression, charts and graphs stay clear and readable." }]),

  v("compress-pdf-thesis", "Compress PDF Thesis", "Academic Thesis",
    "Compress PDF Thesis — Reduce Academic Document Size",
    "Shrink PDF thesis documents for submission portals. Free compression tool.",
    ["compress pdf thesis", "reduce thesis file size", "shrink academic pdf", "thesis pdf compressor"],
    categories.document,
    "Academic theses with research figures, graphs, and images can exceed submission portal limits. Compress to fit.",
    "Most university submission systems accept PDFs up to 10–50 MB. Check your institution's requirements.",
    [{ q: "What is the typical thesis submission limit?", a: "Most universities accept 10–100 MB. Check your specific submission portal." }, { q: "Will figures and graphs stay clear?", a: "At moderate compression, academic figures remain publication-quality." }]),

  v("compress-pdf-manual", "Compress PDF Manual", "Manuals & Guides",
    "Compress PDF Manual — Reduce User Guide Size",
    "Shrink PDF manuals and user guides for web download. Free compression.",
    ["compress pdf manual", "reduce manual size", "shrink user guide pdf", "compress instruction manual"],
    categories.document,
    "Product manuals and user guides with screenshots and diagrams can be very large. Compress them for faster customer downloads.",
    "Manuals with lots of screenshots see the biggest improvements — often 60–80% reduction.",
    [{ q: "Will screenshots in the manual stay readable?", a: "Yes. At moderate compression, screenshots and text remain clear." }, { q: "Can I compress a 200-page manual?", a: "Yes. PDF Minify handles documents up to 50 MB." }]),

  v("compress-pdf-brochure", "Compress PDF Brochure", "Brochures",
    "Compress PDF Brochure — Reduce Marketing PDF Size",
    "Shrink PDF brochures and marketing materials for email distribution. Free tool.",
    ["compress pdf brochure", "reduce brochure size", "shrink marketing pdf", "compress flyer pdf"],
    categories.document,
    "Marketing brochures are typically image-heavy — full-page photos, product images, and design elements. They compress significantly.",
    "Full-color brochures often compress by 50–70% while remaining visually appealing.",
    [{ q: "Will print quality be affected?", a: "For web/email sharing, quality is excellent. For professional printing, keep the original." }, { q: "Can I compress a multi-page catalog?", a: "Yes. Catalogs with product images see great compression results." }]),

  v("compress-pdf-portfolio", "Compress PDF Portfolio", "Portfolios",
    "Compress PDF Portfolio — Reduce Design Portfolio Size",
    "Shrink your design/art portfolio PDF for sharing and submissions. Free compression.",
    ["compress pdf portfolio", "reduce portfolio size", "shrink design portfolio", "portfolio pdf compressor"],
    categories.document,
    "Design portfolios contain high-resolution images, artwork, and photography. They're often 50+ MB. Compress for email sharing.",
    "Portfolios for web viewing don't need print-level resolution. Moderate compression saves space without visible quality loss on screens.",
    [{ q: "Will my artwork look good after compression?", a: "On screens, yes. For print submissions, keep the original high-resolution version." }, { q: "How much can I reduce a portfolio?", a: "Image-heavy portfolios typically compress by 50–80%." }]),

  v("compress-pdf-newsletter", "Compress PDF Newsletter", "Newsletters",
    "Compress PDF Newsletter — Reduce for Email Distribution",
    "Shrink PDF newsletters for mass email distribution. Faster delivery, lower bandwidth.",
    ["compress pdf newsletter", "reduce newsletter size", "shrink newsletter pdf", "email newsletter pdf"],
    categories.document,
    "Newsletters with images and formatted layouts can be large. Compress them so they arrive quickly in every inbox.",
    "For email newsletters, aim for under 3 MB so they don't get blocked by spam filters.",
    [{ q: "Why compress newsletters?", a: "Smaller files mean faster delivery, less bandwidth, and fewer bounced emails." }, { q: "Will the layout be preserved?", a: "Yes. PDF Minify preserves the visual layout of your newsletter." }]),

  v("compress-pdf-form", "Compress PDF Form", "Forms",
    "Compress PDF Form — Reduce Fillable Form Size",
    "Shrink PDF forms for faster loading and sharing. Free online compressor.",
    ["compress pdf form", "reduce form pdf size", "shrink fillable pdf", "compress pdf application form"],
    categories.document,
    "PDF forms with backgrounds, logos, and formatting can be larger than expected. Compress them for easier distribution.",
    "Note: Compression flattens the PDF, so fillable fields may not remain interactive. Use for final/signed forms.",
    [{ q: "Will fillable fields still work?", a: "No. Compression flattens the PDF. Use this for finalized forms, not blank fillable ones." }, { q: "Can I compress government forms?", a: "Yes. Compress filled/signed government forms for submission." }]),

  v("compress-pdf-certificate", "Compress PDF Certificate", "Certificates",
    "Compress PDF Certificate — Reduce Certificate File Size",
    "Shrink PDF certificates for email sharing and digital storage. Free tool.",
    ["compress pdf certificate", "reduce certificate size", "shrink certificate pdf", "compress diploma pdf"],
    categories.document,
    "Certificates with ornate designs, signatures, and seals can be several MB. Compress for easy sharing.",
    "Single-page certificates typically compress to under 200 KB — perfect for email attachments.",
    [{ q: "Will the certificate design stay intact?", a: "Yes. The visual appearance is preserved during compression." }, { q: "Can I compress a diploma PDF?", a: "Yes. Diplomas with images and seals compress well." }]),

  v("compress-pdf-receipt", "Compress PDF Receipt", "Receipts",
    "Compress PDF Receipt — Reduce for Storage",
    "Shrink PDF receipts and purchase confirmations. Save storage space.",
    ["compress pdf receipt", "reduce receipt size", "shrink receipt pdf", "compress purchase receipt"],
    categories.document,
    "Digital receipts accumulate over time. Compress them to save storage space without losing the information you need.",
    "Receipts are typically small, but if you have hundreds, the savings add up.",
    [{ q: "Are receipts worth compressing?", a: "Individual receipts are small, but batch compressing hundreds saves significant space." }, { q: "Can I compress bank statements?", a: "Yes. Bank statement PDFs compress well, especially if they contain logos." }]),

  v("compress-pdf-blueprint", "Compress PDF Blueprint", "Blueprints & Plans",
    "Compress PDF Blueprint — Reduce CAD/Architecture File Size",
    "Shrink large PDF blueprints and architectural plans. Free browser-based compressor.",
    ["compress pdf blueprint", "reduce blueprint size", "shrink cad pdf", "compress architectural plan pdf"],
    categories.document,
    "Architectural blueprints and CAD exports as PDF can be enormous — often 50+ MB per sheet. Compression makes sharing practical.",
    "Blueprints with detailed line drawings compress well. Set quality to medium for the best balance.",
    [{ q: "Will fine lines and text stay visible?", a: "Yes, at moderate compression. Extreme compression may affect very fine details." }, { q: "Can I compress multi-sheet plans?", a: "Yes. PDF Minify handles large files up to 50 MB." }]),

  v("compress-pdf-medical-records", "Compress PDF Medical Records", "Medical Records",
    "Compress PDF Medical Records — Reduce for Secure Sharing",
    "Shrink medical PDF records for secure email or portal sharing. Free, 100% browser-based.",
    ["compress pdf medical records", "reduce medical pdf size", "shrink health records pdf", "compress medical document"],
    categories.document,
    "Medical records with scan images, X-rays, and lab results can be very large. Compression helps share them within portal limits.",
    "Your files never leave your device — important for sensitive medical information.",
    [{ q: "Is it safe for medical documents?", a: "Yes. PDF Minify processes everything in your browser. No files are uploaded to any server." }, { q: "Will X-ray images still be readable?", a: "At moderate compression, medical images remain diagnostic-quality for sharing." }]),

  v("compress-pdf-tax-documents", "Compress PDF Tax Documents", "Tax Documents",
    "Compress PDF Tax Documents — Reduce for Filing",
    "Shrink tax PDFs for electronic filing and email to accountants. Free, private tool.",
    ["compress pdf tax documents", "reduce tax form size", "shrink tax pdf", "compress tax return pdf"],
    categories.document,
    "Tax returns, W-2s, and supporting documents are often scanned PDFs. Compress them for easier electronic filing.",
    "Tax portals often have 5–10 MB limits. Compress scanned documents to fit.",
    [{ q: "Is it secure for tax documents?", a: "Yes. Everything is processed in your browser. No data is sent to any server." }, { q: "Can I compress multiple tax forms at once?", a: "Yes. Drop up to 20 files and download them all as a ZIP." }]),

  v("compress-pdf-photo-book", "Compress PDF Photo Book", "Photo Books",
    "Compress PDF Photo Book — Reduce Image-Heavy PDF",
    "Shrink PDF photo books and albums for sharing. Maximum compression for image-heavy files.",
    ["compress pdf photo book", "reduce photo book size", "shrink photo album pdf", "compress image heavy pdf"],
    categories.document,
    "Photo books and albums exported as PDF are among the largest files — often 100+ MB. Compression is essential for sharing.",
    "Photo books see the biggest reduction — often 70–80% because they're almost entirely images.",
    [{ q: "How much can a photo book be compressed?", a: "Photo-heavy PDFs typically see 60–80% reduction." }, { q: "Will photo quality be acceptable?", a: "For screen viewing and sharing, yes. For reprinting, keep the original." }]),

  // ── PLATFORM & DEVICE (20) ───────────────────────────────────────────────
  v("compress-pdf-on-mac", "Compress PDF on Mac", "Mac / macOS",
    "Compress PDF on Mac — Free Online Tool (No Software)",
    "Reduce PDF file size on Mac using your browser. No app installation needed.",
    ["compress pdf on mac", "mac pdf compressor", "reduce pdf mac", "shrink pdf macbook"],
    categories.platform,
    "No need to install software on your Mac. PDF Minify works directly in Safari, Chrome, or any browser on macOS.",
    "Works with Safari, Chrome, Firefox, and Edge on macOS. No downloads or extensions needed.",
    [{ q: "Do I need to install an app?", a: "No. PDF Minify works in any modern browser on Mac." }, { q: "Does it work on Safari?", a: "Yes. PDF Minify is fully compatible with Safari on macOS." }]),

  v("compress-pdf-on-windows", "Compress PDF on Windows", "Windows PC",
    "Compress PDF on Windows — Free Browser-Based Tool",
    "Reduce PDF file size on Windows using your browser. No software needed.",
    ["compress pdf on windows", "windows pdf compressor", "reduce pdf windows", "shrink pdf windows pc"],
    categories.platform,
    "No need to download Acrobat or other paid software. PDF Minify works in Chrome, Edge, Firefox, or any browser on Windows.",
    "Microsoft Edge works great with PDF Minify — it's already installed on every Windows PC.",
    [{ q: "Do I need Adobe Acrobat?", a: "No. PDF Minify is a free alternative that works in your browser." }, { q: "Which browser works best?", a: "Chrome and Edge both work perfectly. Any modern browser will do." }]),

  v("compress-pdf-on-iphone", "Compress PDF on iPhone", "iPhone / iOS",
    "Compress PDF on iPhone — Reduce PDF Size on Mobile",
    "Shrink PDF files directly on your iPhone using Safari. No app required.",
    ["compress pdf on iphone", "iphone pdf compressor", "reduce pdf iphone", "shrink pdf ios"],
    categories.platform,
    "Need to send a PDF from your iPhone but it's too large? Open PDF Minify in Safari, upload your file, and download the compressed version.",
    "On iPhone, tap 'Choose PDF files', then select from Files or iCloud Drive.",
    [{ q: "Can I compress PDFs on iPhone without an app?", a: "Yes. Just open pdfminify.com in Safari and upload your PDF." }, { q: "Where does the compressed file go?", a: "It downloads to your Files app. You can then share it from there." }]),

  v("compress-pdf-on-android", "Compress PDF on Android", "Android",
    "Compress PDF on Android — Free Mobile PDF Compressor",
    "Reduce PDF file size on Android phones and tablets. No app installation needed.",
    ["compress pdf on android", "android pdf compressor", "reduce pdf android", "shrink pdf android phone"],
    categories.platform,
    "Compress PDFs directly on your Android device using Chrome or any browser. No app needed — just visit the site and upload.",
    "On Android, tap 'Choose PDF files' and select from Downloads, Drive, or any file manager.",
    [{ q: "Does it work on Android tablets?", a: "Yes. PDF Minify works on any Android device with a browser." }, { q: "Do I need to install an app?", a: "No. It's a website that works in your mobile browser." }]),

  v("compress-pdf-on-ipad", "Compress PDF on iPad", "iPad",
    "Compress PDF on iPad — Reduce PDF Size on Tablet",
    "Shrink PDF documents on iPad using Safari. Free, no app needed.",
    ["compress pdf on ipad", "ipad pdf compressor", "reduce pdf ipad", "shrink pdf ipad safari"],
    categories.platform,
    "iPad users often work with PDFs for study, business, and creative work. Compress directly in Safari — no app required.",
    "iPadOS supports drag-and-drop — you can drag PDFs from Files directly into the upload zone.",
    [{ q: "Can I drag and drop on iPad?", a: "Yes. iPadOS supports drag-and-drop from the Files app into Safari." }, { q: "Does it work offline?", a: "You need an internet connection to load the page, but compression happens locally in your browser." }]),

  v("compress-pdf-on-chromebook", "Compress PDF on Chromebook", "Chromebook",
    "Compress PDF on Chromebook — Free Browser Tool",
    "Reduce PDF file size on Chromebook. Perfect for ChromeOS — works entirely in Chrome.",
    ["compress pdf on chromebook", "chromebook pdf compressor", "reduce pdf chromebook", "shrink pdf chromeos"],
    categories.platform,
    "Chromebooks run everything in the browser — making PDF Minify a perfect fit. No Android app or Linux subsystem needed.",
    "ChromeOS works seamlessly with web tools like PDF Minify. Just open the site in Chrome.",
    [{ q: "Why is this good for Chromebook?", a: "Chromebooks are browser-first devices. PDF Minify is a browser-first tool — perfect match." }, { q: "Do I need the Play Store?", a: "No. Just use the Chrome browser directly." }]),

  v("compress-pdf-on-linux", "Compress PDF on Linux", "Linux",
    "Compress PDF on Linux — Free Online Alternative to Ghostscript",
    "Reduce PDF size on Linux without command-line tools. Free browser-based compressor.",
    ["compress pdf on linux", "linux pdf compressor", "reduce pdf linux", "compress pdf without ghostscript"],
    categories.platform,
    "Instead of wrestling with Ghostscript command-line options, just open PDF Minify in Firefox or Chrome on Linux.",
    "Works on Ubuntu, Fedora, Arch, and any Linux distro with a modern browser.",
    [{ q: "Is this better than Ghostscript?", a: "For quick compression without command-line knowledge, yes. Ghostscript offers more fine-grained control." }, { q: "Which browser works on Linux?", a: "Firefox, Chrome, Chromium, and Brave all work perfectly." }]),

  v("compress-pdf-without-adobe", "Compress PDF Without Adobe", "No Adobe",
    "Compress PDF Without Adobe Acrobat — Free Alternative",
    "Reduce PDF size without Adobe Acrobat. Free online compressor, no software needed.",
    ["compress pdf without adobe", "free alternative to adobe compress", "reduce pdf no acrobat", "pdf compressor no adobe"],
    categories.platform,
    "Adobe Acrobat Pro charges $20+/month for PDF compression. PDF Minify does it free, with no account or software required.",
    "Unlike Adobe, your files stay on your device. No cloud processing, no account, no subscription.",
    [{ q: "How does this compare to Adobe Acrobat?", a: "PDF Minify is free and browser-based. Adobe offers more editing features but costs money." }, { q: "Is the compression quality comparable?", a: "For standard compression, results are comparable. Adobe may offer more fine-grained control." }]),

  v("compress-pdf-without-software", "Compress PDF Without Software", "No Software",
    "Compress PDF Without Installing Software",
    "Reduce PDF file size online — no downloads, no installation, no registration.",
    ["compress pdf without software", "online pdf compressor no install", "reduce pdf no download", "web based pdf compressor"],
    categories.platform,
    "Don't want to install anything? PDF Minify runs entirely in your browser. Open the site, drop your PDF, download the result.",
    "This is ideal for work computers where you can't install software, or when you need a quick one-off compression.",
    [{ q: "Why not install a desktop app?", a: "Web tools are instant — no download, no installation, no updates to manage." }, { q: "Is it as good as desktop software?", a: "For compression, yes. Desktop apps may offer additional editing features." }]),

  v("compress-pdf-offline", "Compress PDF Offline", "Offline / Privacy",
    "Compress PDF Offline — 100% Browser-Based, No Internet Upload",
    "Your PDFs never leave your device. Compression happens locally in your browser.",
    ["compress pdf offline", "pdf compression no upload", "local pdf compressor", "private pdf compression"],
    categories.platform,
    "While you need internet to load the page, once loaded, all compression happens offline in your browser. No files are ever sent anywhere.",
    "For sensitive documents, this is the safest option — your files never touch a server.",
    [{ q: "Does my file really stay on my device?", a: "Yes. The JavaScript code runs locally. Your PDF is processed in your browser and never uploaded." }, { q: "Can I use this without internet?", a: "You need internet to load the page initially, but compression itself is offline." }]),

  // ── INDUSTRY & USE CASE (30) ─────────────────────────────────────────────
  v("compress-pdf-for-job-application", "Compress PDF for Job Application", "Job Applications",
    "Compress PDF for Job Application — Fit Upload Limits",
    "Shrink resume and cover letter PDFs for job portal uploads. Free, private.",
    ["compress pdf job application", "reduce resume for job portal", "shrink pdf for hiring", "job application pdf size"],
    categories.industry,
    "Job portals (LinkedIn, Indeed, Workday) often limit uploads to 1–10 MB. Compress your resume and cover letter to fit.",
    "Most ATS (Applicant Tracking Systems) accept PDFs up to 5 MB. Aim for under 2 MB for fastest processing.",
    [{ q: "What size should my resume be?", a: "Under 2 MB is ideal for most job portals and ATS systems." }, { q: "Will ATS still read my compressed resume?", a: "Compression converts pages to images, which may affect ATS text parsing. For ATS-critical applications, keep text-based PDFs." }]),

  v("compress-pdf-for-printing", "Compress PDF for Printing", "Printing",
    "Compress PDF for Printing — Optimize for Print Shops",
    "Reduce PDF size for faster transfer to print shops and printers.",
    ["compress pdf for printing", "optimize pdf print", "reduce pdf for printer", "print ready pdf compress"],
    categories.industry,
    "Print-ready PDFs are often very large. Compress for faster transfer, but use moderate settings to maintain print quality.",
    "For printing, use the right side of the compression slider to maintain higher quality. Left side is for screen viewing only.",
    [{ q: "Will compression affect print quality?", a: "At moderate settings, print quality is preserved. For premium printing, keep the original." }, { q: "What DPI is maintained?", a: "Moderate compression typically maintains 150–200 DPI — sufficient for most commercial printing." }]),

  v("compress-pdf-for-archiving", "Compress PDF for Archiving", "Archiving",
    "Compress PDF for Archiving — Save Long-Term Storage Space",
    "Shrink PDFs for long-term digital archiving. Reduce storage costs.",
    ["compress pdf for archiving", "archive pdf smaller", "reduce pdf for storage", "long term pdf storage"],
    categories.industry,
    "Archiving thousands of PDFs? Compression can save gigabytes of storage while keeping documents accessible.",
    "For archiving, maximum compression is usually acceptable — you're optimizing for storage, not print quality.",
    [{ q: "Is compressed PDF suitable for long-term archiving?", a: "Yes. Compressed PDFs are standard PDFs that can be read by any PDF viewer." }, { q: "How much storage can I save?", a: "If you compress all documents by 60%, a 100 GB archive becomes about 40 GB." }]),

  v("compress-pdf-for-court", "Compress PDF for Court Filing", "Legal / Court",
    "Compress PDF for Court Filing — Meet e-Filing Size Limits",
    "Reduce PDF size for electronic court filing systems. Most courts limit to 25–50 MB.",
    ["compress pdf for court", "e-filing pdf size limit", "court document pdf compress", "legal filing pdf reduce"],
    categories.industry,
    "Electronic court filing systems (e.g., PACER, CM/ECF) have strict size limits. Compress your legal documents to comply.",
    "Federal courts typically limit to 35 MB per filing. Check your specific court's requirements.",
    [{ q: "What are typical court size limits?", a: "Federal: 35 MB, state varies (10–50 MB). Check your court's e-filing guidelines." }, { q: "Is compressed PDF court-admissible?", a: "Yes. Courts accept standard PDFs. The content is preserved." }]),

  v("compress-pdf-for-university", "Compress PDF for University", "University",
    "Compress PDF for University Submission — Reduce Assignment Size",
    "Shrink PDF assignments and papers for university portals. Free tool.",
    ["compress pdf for university", "reduce assignment pdf", "university upload pdf limit", "compress pdf for school"],
    categories.industry,
    "University portals (Canvas, Blackboard, Moodle, Turnitin) often limit uploads to 10–40 MB. Compress to submit on time.",
    "Turnitin accepts PDFs up to 40 MB. Canvas and Blackboard limits vary by institution.",
    [{ q: "What is the typical university upload limit?", a: "Usually 10–40 MB depending on the platform and institution settings." }, { q: "Will my professor see quality loss?", a: "At moderate compression, the difference is negligible on screen." }]),

  v("compress-pdf-for-government", "Compress PDF for Government Portal", "Government",
    "Compress PDF for Government Portals — Meet Upload Requirements",
    "Reduce PDF size for government form submissions and portals. Free, private tool.",
    ["compress pdf for government", "government portal pdf limit", "reduce pdf government form", "compress pdf for visa"],
    categories.industry,
    "Government portals (visa applications, tax filings, permit requests) have strict file size limits, often 1–10 MB.",
    "Government portals have some of the strictest limits. Always check the exact requirement before compressing.",
    [{ q: "What size do government portals accept?", a: "Varies widely: 1–10 MB for most, some accept up to 25 MB." }, { q: "Is it safe for sensitive government documents?", a: "Yes. Files are processed locally in your browser and never uploaded." }]),

  v("compress-pdf-for-insurance", "Compress PDF for Insurance Claim", "Insurance",
    "Compress PDF for Insurance Claims — Reduce Document Size",
    "Shrink PDFs for insurance claim submissions and portals. Free tool.",
    ["compress pdf for insurance", "insurance claim pdf size", "reduce pdf insurance portal", "compress claim documents"],
    categories.industry,
    "Insurance portals often require scanned documents — medical records, photos, repair estimates — which can be very large.",
    "Insurance portals typically accept 5–25 MB. Compress scanned documents to fit easily.",
    [{ q: "Can I compress medical records for insurance?", a: "Yes. Compress them locally for maximum privacy." }, { q: "Will scanned photos still be clear?", a: "At moderate compression, photos remain clear enough for claims processing." }]),

  v("compress-pdf-for-real-estate", "Compress PDF for Real Estate", "Real Estate",
    "Compress PDF for Real Estate — Reduce Listing & Contract Size",
    "Shrink large real estate PDFs — listings, contracts, inspection reports.",
    ["compress pdf real estate", "reduce listing pdf", "shrink property pdf", "compress inspection report"],
    categories.industry,
    "Real estate documents (listings with photos, inspection reports, floor plans) are often very large. Compress for email and portal sharing.",
    "Property listing PDFs with many photos see the biggest compression — often 60–80% reduction.",
    [{ q: "Will property photos still look good?", a: "On screens and for email sharing, yes. For print materials, keep the originals." }, { q: "Can I compress inspection reports?", a: "Yes. Reports with photos compress well." }]),

  v("compress-pdf-for-healthcare", "Compress PDF for Healthcare", "Healthcare",
    "Compress PDF for Healthcare — Reduce Medical Document Size",
    "Shrink medical PDFs for patient portal uploads and secure sharing.",
    ["compress pdf healthcare", "medical pdf compress", "reduce health document size", "patient portal pdf limit"],
    categories.industry,
    "Healthcare portals often have strict upload limits. Compress medical records, lab results, and referral letters to fit.",
    "100% browser-based — your medical data never leaves your device. HIPAA-compatible process.",
    [{ q: "Is this HIPAA compliant?", a: "Your files never leave your device, so there is no data transmission to worry about." }, { q: "Can I compress X-ray PDFs?", a: "Yes. X-ray PDFs with embedded images compress well." }]),

  v("compress-pdf-for-accounting", "Compress PDF for Accounting", "Accounting",
    "Compress PDF for Accounting — Reduce Financial Document Size",
    "Shrink financial PDFs — statements, receipts, reports — for email and archiving.",
    ["compress pdf accounting", "reduce financial pdf", "shrink accounting documents", "compress tax pdf"],
    categories.industry,
    "Accountants handle thousands of PDFs — receipts, bank statements, tax forms. Batch compression saves storage and email space.",
    "Use batch mode to compress all documents at once. Download as ZIP for organized archiving.",
    [{ q: "Can I compress an entire folder of receipts?", a: "Drop up to 20 PDFs at once. For more, compress in batches." }, { q: "Is it safe for financial documents?", a: "Yes. Everything is processed locally — no server uploads." }]),

  v("compress-pdf-for-education", "Compress PDF for Education", "Education",
    "Compress PDF for Education — Reduce Learning Material Size",
    "Shrink educational PDFs — worksheets, textbooks, handouts — for LMS uploads.",
    ["compress pdf education", "reduce worksheet pdf", "shrink textbook pdf", "compress pdf for lms"],
    categories.industry,
    "Teachers and professors often share PDFs through LMS platforms. Compress materials so students can download them quickly.",
    "Canvas, Blackboard, and Google Classroom all handle smaller files better. Students on mobile will appreciate faster downloads.",
    [{ q: "Will students see quality differences?", a: "On laptops and phones, the difference is negligible at moderate compression." }, { q: "Can I compress textbook chapters?", a: "Yes. Textbook PDFs with images and diagrams compress well." }]),

  v("compress-pdf-for-marketing", "Compress PDF for Marketing", "Marketing",
    "Compress PDF for Marketing — Reduce Campaign Asset Size",
    "Shrink marketing PDFs — brochures, whitepapers, case studies — for distribution.",
    ["compress pdf marketing", "reduce whitepaper size", "shrink case study pdf", "compress marketing materials"],
    categories.industry,
    "Marketing teams create beautiful, image-heavy PDFs. Compress them for email campaigns, lead magnets, and website downloads.",
    "For lead magnets behind forms, smaller PDFs mean faster delivery and better user experience.",
    [{ q: "Will brand colors look correct?", a: "Yes. Compression does not alter colors." }, { q: "Can I compress a whitepaper with charts?", a: "Yes. Charts and infographics remain clear at moderate compression." }]),

  v("compress-pdf-for-hr", "Compress PDF for HR", "Human Resources",
    "Compress PDF for HR — Reduce Employee Document Size",
    "Shrink HR PDFs — policies, handbooks, onboarding materials — for distribution.",
    ["compress pdf hr", "reduce hr document size", "shrink employee handbook pdf", "compress onboarding materials"],
    categories.industry,
    "HR departments distribute policies, handbooks, and forms to all employees. Smaller PDFs save email bandwidth and storage.",
    "Employee handbooks with photos and formatting typically compress by 40–60%.",
    [{ q: "Can I compress the entire employee handbook?", a: "Yes. Handbooks with images and formatting compress well." }, { q: "Will fillable forms still work?", a: "Compression flattens the PDF. Use for finalized documents, not blank forms." }]),

  v("compress-pdf-for-construction", "Compress PDF for Construction", "Construction",
    "Compress PDF for Construction — Reduce Blueprint & Plan Size",
    "Shrink construction PDFs — blueprints, plans, specs — for field sharing.",
    ["compress pdf construction", "reduce blueprint pdf", "shrink construction plan", "compress spec sheets"],
    categories.industry,
    "Construction documents are often very large. Compress them so field workers can access them quickly on tablets and phones.",
    "Blueprints and plans with line drawings compress well. Photos of jobsites may lose some detail at high compression.",
    [{ q: "Will fine blueprint details be lost?", a: "At moderate compression, details remain clear. Use lower compression for critical measurements." }, { q: "Can field workers access these on tablets?", a: "Yes. Smaller files load faster on tablets, even with slow site WiFi." }]),

  // ── QUALITY & SETTINGS (15) ──────────────────────────────────────────────
  v("compress-pdf-without-losing-quality", "Compress PDF Without Losing Quality", "No Quality Loss",
    "Compress PDF Without Losing Quality — Lossless-Like Compression",
    "Reduce PDF file size while maintaining visual quality. Smart compression algorithm.",
    ["compress pdf without losing quality", "lossless pdf compression", "reduce pdf keep quality", "compress pdf no quality loss"],
    categories.quality,
    "PDF Minify's moderate compression setting reduces file size significantly while keeping visual quality nearly identical to the original.",
    "Use the right half of the compression slider for the best quality-to-size ratio.",
    [{ q: "Is the compression truly lossless?", a: "It's not bit-for-bit lossless, but at moderate settings, the visual difference is imperceptible." }, { q: "What setting preserves the most quality?", a: "Move the slider to the right for maximum quality with moderate size reduction." }]),

  v("compress-pdf-maximum", "Maximum PDF Compression", "Maximum Compression",
    "Maximum PDF Compression — Smallest Possible File Size",
    "Achieve the smallest possible PDF file size. Aggressive compression for storage and sharing.",
    ["maximum pdf compression", "smallest pdf possible", "extreme pdf compression", "aggressive pdf reduce"],
    categories.quality,
    "When file size matters more than image quality, use maximum compression. Text remains readable but images will be noticeably lower resolution.",
    "Move the slider all the way to the left for maximum compression. Best for archiving and quick sharing.",
    [{ q: "When should I use maximum compression?", a: "When you need the absolute smallest file — for email, archiving, or very strict upload limits." }, { q: "How much quality do I lose?", a: "Text stays clear. Images will be lower resolution but still viewable." }]),

  v("compress-pdf-high-quality", "Compress PDF High Quality", "High Quality",
    "Compress PDF in High Quality — Minimal Size Reduction, Maximum Fidelity",
    "Reduce PDF size slightly while preserving near-original quality. Perfect for important documents.",
    ["compress pdf high quality", "gentle pdf compression", "reduce pdf minimal quality loss", "high quality pdf smaller"],
    categories.quality,
    "Not all compressions need to be aggressive. High-quality mode reduces file size by 20–40% while keeping images nearly untouched.",
    "Move the slider to the right (80–100%) for high-quality compression.",
    [{ q: "How much can I save in high-quality mode?", a: "Typically 20–40% reduction, depending on the document content." }, { q: "Is this good for professional documents?", a: "Yes. High-quality compression is ideal for client-facing documents and presentations." }]),

  v("compress-pdf-fast", "Fast PDF Compression", "Fast Compression",
    "Fast PDF Compression — Instant Results in Your Browser",
    "Compress PDFs in seconds with instant browser-based processing. No waiting.",
    ["fast pdf compression", "instant pdf compress", "quick pdf reduce", "compress pdf seconds"],
    categories.quality,
    "PDF Minify processes files directly in your browser — no upload, no waiting for server processing. Results appear in seconds.",
    "Most PDFs compress in under 10 seconds. Larger files (40+ MB) may take up to a minute.",
    [{ q: "How fast is the compression?", a: "Most PDFs finish in 2–10 seconds. Very large files may take up to a minute." }, { q: "Why is it so fast?", a: "Everything runs locally in your browser. No file upload, no server queue, no waiting." }]),

  v("compress-pdf-securely", "Compress PDF Securely", "Secure Compression",
    "Compress PDF Securely — 100% Private, No Upload",
    "Your PDFs never leave your device. Secure, private compression in your browser.",
    ["secure pdf compression", "private pdf compressor", "compress pdf no upload", "safe pdf compression tool"],
    categories.quality,
    "PDF Minify is the most private PDF compressor available. Your files are processed entirely in your browser — nothing is ever sent to a server.",
    "For confidential documents (legal, medical, financial), this is the safest compression method.",
    [{ q: "How can I verify files aren't uploaded?", a: "Open browser DevTools (Network tab) — you'll see no file upload requests during compression." }, { q: "Is this suitable for confidential documents?", a: "Yes. This is the most private way to compress PDFs online." }]),

  v("compress-pdf-batch", "Batch Compress PDF", "Batch Processing",
    "Batch Compress PDF — Multiple Files at Once",
    "Compress up to 20 PDF files simultaneously. Download all as a ZIP archive.",
    ["batch compress pdf", "compress multiple pdfs", "bulk pdf compression", "compress many pdf files"],
    categories.batch,
    "Drop up to 20 PDF files at once and compress them all in one run. Download individually or as a ZIP archive.",
    "For more than 20 files, process them in batches. Each batch takes just seconds.",
    [{ q: "What is the batch limit?", a: "20 files per batch, each up to 50 MB." }, { q: "Can I download all at once?", a: "Yes. Use the 'Download all' button to get a ZIP archive of all compressed files." }]),

  v("compress-pdf-and-download-zip", "Compress PDF & Download as ZIP", "ZIP Download",
    "Compress PDF & Download as ZIP — Batch Compression",
    "Compress multiple PDFs and download them all as a single ZIP archive.",
    ["compress pdf download zip", "pdf compressor zip", "batch compress pdf zip download", "multiple pdf to zip"],
    categories.batch,
    "When you compress multiple PDFs, PDF Minify lets you download them all as a single ZIP archive — organized and ready to share.",
    "The ZIP file uses the naming convention: filename-min.pdf for each compressed file.",
    [{ q: "What is the ZIP file naming convention?", a: "Each compressed file is named original-name-min.pdf inside the ZIP." }, { q: "Can I compress and ZIP 20 files?", a: "Yes. That's the maximum batch size." }]),

  // ── ADDITIONAL LONG-TAIL VARIANTS (50+) ──────────────────────────────────
  v("compress-large-pdf", "Compress Large PDF Files", "Large Files",
    "Compress Large PDF — Reduce Files Up to 50 MB",
    "Shrink large PDF documents up to 50 MB. Free browser-based compression.",
    ["compress large pdf", "reduce big pdf file", "shrink large pdf document", "large pdf compressor"],
    categories.general,
    "PDF Minify handles files up to 50 MB — large enough for most presentations, reports, and scanned documents.",
    "Files over 30 MB may take a bit longer to process. The compression itself is still fast.",
    [{ q: "What is the maximum file size?", a: "50 MB per file. You can process up to 20 files per batch." }, { q: "How long does a 50 MB file take?", a: "Typically 30–60 seconds depending on your device speed." }]),

  v("reduce-pdf-file-size", "Reduce PDF File Size", "Reduce Size",
    "Reduce PDF File Size Online — Free & Instant",
    "Make your PDF files smaller online. Free browser-based tool, no registration.",
    ["reduce pdf file size", "make pdf smaller", "decrease pdf size", "pdf file size reducer"],
    categories.general,
    "PDF Minify reduces file size by intelligently compressing images within your PDF while preserving text and layout.",
    "The slider gives you control: left for smallest file, right for best quality.",
    [{ q: "How does PDF Minify reduce file size?", a: "It re-renders pages as optimized JPEG images, significantly reducing embedded image data." }, { q: "Does it work on all PDFs?", a: "Most PDFs with images compress well. Text-only PDFs are already small." }]),

  v("shrink-pdf-file", "Shrink PDF File", "Shrink PDF",
    "Shrink PDF File Online — Free & No Signup",
    "Make your PDF documents smaller. No registration, no upload to server.",
    ["shrink pdf file", "shrink pdf online", "shrink pdf document", "pdf shrinker free"],
    categories.general,
    "Shrink your PDF files without creating an account or uploading to any server. Everything happens privately in your browser.",
    "For the quickest experience, drag and drop your files directly into the upload zone.",
    [{ q: "Do I need to create an account?", a: "No. PDF Minify is completely free with no registration required." }, { q: "Is there a daily limit?", a: "No. Compress as many files as you want, as often as you want." }]),

  v("make-pdf-smaller", "Make PDF Smaller", "Smaller PDF",
    "Make PDF Smaller — Free Online PDF Size Reducer",
    "Reduce your PDF file size online. Drag, drop, and download — instant results.",
    ["make pdf smaller", "pdf smaller online", "reduce my pdf", "make pdf file smaller free"],
    categories.general,
    "The simplest way to make your PDF smaller. Drop your file, wait a few seconds, and download the compressed version.",
    "Works for any PDF — resumes, reports, presentations, invoices, contracts, and more.",
    [{ q: "How much smaller will my PDF be?", a: "Typically 30–80% smaller, depending on content." }, { q: "Is there a limit on how many I can compress?", a: "No limit. Compress as many as you need." }]),

  v("optimize-pdf-file-size", "Optimize PDF File Size", "Optimize PDF",
    "Optimize PDF File Size — Smart Compression",
    "Optimize PDF files for the best balance of size and quality. Free tool.",
    ["optimize pdf file size", "pdf optimization", "optimize pdf online", "best pdf compression"],
    categories.general,
    "Optimization isn't just about making files smaller — it's about finding the right balance. PDF Minify's slider gives you full control.",
    "The middle position is a great starting point — it balances size and quality for most documents.",
    [{ q: "What's the difference between compress and optimize?", a: "Optimization implies a smart balance. Use moderate settings for the best results." }, { q: "Can I fine-tune the compression level?", a: "Yes. The slider lets you choose anywhere from maximum compression to maximum quality." }]),

  v("pdf-file-too-large", "PDF File Too Large — How to Fix", "Fix Large PDF",
    "PDF File Too Large? Reduce Size in Seconds",
    "Is your PDF file too large to email or upload? Compress it instantly for free.",
    ["pdf file too large", "pdf too big to email", "pdf too big to upload", "fix large pdf file"],
    categories.general,
    "Getting 'file too large' errors? PDF Minify compresses your PDF so it fits within any upload or email limit.",
    "Start with medium compression. If still too large, move the slider left for more aggressive reduction.",
    [{ q: "Why is my PDF so large?", a: "PDFs with embedded images (photos, scans, charts) are typically the largest. These compress best." }, { q: "Will the error go away after compression?", a: "In most cases, yes. Check the output file size against your specific limit." }]),

  v("compress-pdf-free", "Compress PDF Free", "Free Tool",
    "Compress PDF Free — No Cost, No Signup, No Limits",
    "100% free PDF compression. No hidden fees, no registration, no usage limits.",
    ["compress pdf free", "free pdf compressor", "compress pdf online free", "pdf reducer free no signup"],
    categories.general,
    "PDF Minify is completely free. No trial periods, no credit card, no signup. Just open the site and start compressing.",
    "Unlike many 'free' tools, PDF Minify has no daily limits, no watermarks, and no upselling.",
    [{ q: "Is it really free?", a: "Yes. No hidden costs, no premium tiers, no credits to buy." }, { q: "How does it make money?", a: "The site is supported by optional advertising." }]),

  v("compress-pdf-online", "Compress PDF Online", "Online Tool",
    "Compress PDF Online — No Download, No Install",
    "Compress PDFs directly in your web browser. No software to download or install.",
    ["compress pdf online", "online pdf compressor", "web pdf compression", "compress pdf in browser"],
    categories.general,
    "Open pdfminify.com in any browser, drop your PDF, and download the smaller version. That's it — no downloads needed.",
    "Works on any device with a modern browser — desktop, laptop, tablet, or phone.",
    [{ q: "Which browsers are supported?", a: "Chrome, Firefox, Safari, Edge, Brave — any modern browser." }, { q: "Do I need to download anything?", a: "No. Everything runs in your browser." }]),

  v("best-pdf-compressor", "Best PDF Compressor", "Best Compressor",
    "Best PDF Compressor — Free, Private, and Instant",
    "The best free PDF compressor. 100% browser-based, no upload, no signup.",
    ["best pdf compressor", "top pdf compression tool", "best free pdf reducer", "best online pdf compressor"],
    categories.general,
    "PDF Minify combines privacy (no upload), speed (browser-based), and simplicity (drag & drop) for the best compression experience.",
    "Try it yourself — the difference is immediate. No account, no waiting, no server processing.",
    [{ q: "What makes PDF Minify the best?", a: "Privacy-first design, instant results, and completely free with no limits." }, { q: "How does it compare to other tools?", a: "Most competitors upload your files to a server. PDF Minify never does." }]),

  v("compress-pdf-no-watermark", "Compress PDF No Watermark", "No Watermark",
    "Compress PDF Without Watermark — Clean Output",
    "Compress PDFs without any watermark or branding added. Completely clean output.",
    ["compress pdf no watermark", "pdf compressor no watermark", "reduce pdf without watermark", "free pdf compress clean"],
    categories.general,
    "Many free PDF tools add watermarks to compressed files. PDF Minify never does. Your documents stay clean and professional.",
    "The output PDF has zero branding or watermarks — just your content, smaller.",
    [{ q: "Do any free tools really have no watermark?", a: "PDF Minify genuinely adds no watermark to any compressed file." }, { q: "Is the output file modified in any way?", a: "Pages are re-rendered as optimized images. No text, logos, or watermarks are added." }]),

  v("compress-pdf-no-signup", "Compress PDF No Signup", "No Registration",
    "Compress PDF No Signup — Instant, Anonymous Compression",
    "Compress PDFs without creating an account. No email, no registration, no hassle.",
    ["compress pdf no signup", "compress pdf no registration", "pdf compressor anonymous", "compress pdf no email"],
    categories.general,
    "Just open the site and compress. No account creation, no email verification, no personal data collected.",
    "Your privacy is respected from start to finish — no tracking beyond basic page analytics.",
    [{ q: "Do I need an email address?", a: "No. PDF Minify requires zero personal information." }, { q: "Is there any tracking?", a: "Basic page analytics only. No file data is ever collected." }]),

  v("compress-pdf-no-limit", "Compress PDF No Limit", "Unlimited",
    "Compress PDF With No Limits — Unlimited Free Usage",
    "No daily limits, no file count restrictions. Compress as many PDFs as you want.",
    ["compress pdf no limit", "unlimited pdf compression", "no daily limit pdf compressor", "compress pdf unlimited free"],
    categories.general,
    "Unlike many competitors, PDF Minify has no daily compression limit. Process 1 file or 1000 — it's always free.",
    "The only limit is 20 files per batch and 50 MB per file. But you can run unlimited batches.",
    [{ q: "Is there a daily limit?", a: "No. Compress as many files as you want, every day." }, { q: "Why don't you have limits?", a: "Because compression runs in your browser, there's no server cost per compression." }]),

  v("compress-pdf-for-kindle", "Compress PDF for Kindle", "Kindle",
    "Compress PDF for Kindle — Optimize for E-Reader",
    "Reduce PDF size for Kindle and other e-readers. Smaller files load faster.",
    ["compress pdf kindle", "optimize pdf for kindle", "reduce pdf ereader", "kindle pdf compressor"],
    categories.platform,
    "Large PDFs can be slow to load on Kindle. Compress them for a smoother reading experience.",
    "Kindle handles PDFs up to 50 MB, but smaller files turn pages faster and use less memory.",
    [{ q: "Will it look good on Kindle?", a: "Text remains clear. Images may be slightly lower resolution on e-ink displays." }, { q: "Can I send compressed PDFs to Kindle via email?", a: "Yes. The smaller file size helps stay within email attachment limits." }]),

  v("compress-pdf-for-notion", "Compress PDF for Notion", "Notion",
    "Compress PDF for Notion — Reduce Upload Size",
    "Shrink PDFs for Notion uploads. Free plan has limited storage.",
    ["compress pdf notion", "reduce pdf for notion", "notion pdf upload", "shrink pdf notion workspace"],
    categories.platform,
    "Notion's free plan has limited file upload size (5 MB per file). Compress your PDFs to fit within these limits.",
    "Notion free tier limits uploads to 5 MB per file. Compress your PDFs to fit.",
    [{ q: "What is Notion's file upload limit?", a: "Free: 5 MB per file. Plus: 5 GB total. Business: unlimited." }, { q: "Will embedded PDFs still preview in Notion?", a: "Yes. Compressed PDFs work normally in Notion." }]),

  v("compress-pdf-for-trello", "Compress PDF for Trello", "Trello",
    "Compress PDF for Trello — Fit Card Attachment Limits",
    "Reduce PDF size for Trello card attachments. Free plan limits to 10 MB.",
    ["compress pdf trello", "trello pdf attachment limit", "reduce pdf trello card", "shrink pdf for trello"],
    categories.platform,
    "Trello free accounts limit attachments to 10 MB per file. Compress your PDFs to attach them to cards.",
    "Business Class allows up to 250 MB, but smaller files load faster in the Trello interface.",
    [{ q: "What is Trello's attachment limit?", a: "Free: 10 MB, Standard: 250 MB, Premium: 250 MB." }, { q: "Will the PDF preview in Trello?", a: "Yes. Trello previews attached PDFs normally." }]),

  v("compress-pdf-for-airtable", "Compress PDF for Airtable", "Airtable",
    "Compress PDF for Airtable — Reduce Attachment Size",
    "Shrink PDFs for Airtable record attachments. Save storage space.",
    ["compress pdf airtable", "airtable pdf attachment", "reduce pdf airtable", "shrink pdf for airtable"],
    categories.platform,
    "Airtable bases have storage limits. Compress PDFs before attaching them to records to maximize your available space.",
    "Airtable free tier has limited attachment storage. Every MB you save extends your workspace capacity.",
    [{ q: "What is Airtable's storage limit?", a: "Free: 1 GB, Plus: 5 GB, Pro: 20 GB, Enterprise: 1 TB." }, { q: "Can I bulk attach compressed PDFs?", a: "Compress in batch, then upload to Airtable records individually." }]),

  v("compress-pdf-for-salesforce", "Compress PDF for Salesforce", "Salesforce",
    "Compress PDF for Salesforce — Reduce Document Attachment Size",
    "Shrink PDFs for Salesforce record attachments. Stay within storage limits.",
    ["compress pdf salesforce", "salesforce pdf attachment", "reduce pdf salesforce", "crm pdf compressor"],
    categories.industry,
    "Salesforce storage is expensive. Compress PDFs before attaching them to opportunities, contacts, and cases.",
    "Salesforce charges per GB of storage. Compressing all PDF attachments can significantly reduce costs.",
    [{ q: "How much can I save on Salesforce storage?", a: "If PDFs reduce by 60%, you save proportionally on storage costs." }, { q: "Will Salesforce preview work?", a: "Yes. Compressed PDFs preview normally in Salesforce." }]),

  v("compress-pdf-for-hubspot", "Compress PDF for HubSpot", "HubSpot",
    "Compress PDF for HubSpot — Optimize CRM Attachments",
    "Reduce PDF size for HubSpot email attachments and file manager.",
    ["compress pdf hubspot", "hubspot pdf attachment", "reduce pdf hubspot email", "crm email pdf compressor"],
    categories.industry,
    "HubSpot email attachments and file manager have size limits. Compress PDFs for smoother CRM workflows.",
    "HubSpot email attachments are limited to 20 MB. Compress large proposals and contracts to fit.",
    [{ q: "What is HubSpot's email attachment limit?", a: "HubSpot limits email attachments to 20 MB total." }, { q: "Can I host compressed PDFs in HubSpot?", a: "Yes. Upload to the File Manager and use in emails, landing pages, and CTAs." }]),

  v("compress-pdf-for-zendesk", "Compress PDF for Zendesk", "Zendesk",
    "Compress PDF for Zendesk — Reduce Support Ticket Attachments",
    "Shrink PDFs for Zendesk support tickets. Faster uploads and responses.",
    ["compress pdf zendesk", "zendesk pdf attachment", "reduce pdf support ticket", "compress pdf helpdesk"],
    categories.industry,
    "Support teams handle many PDF attachments daily. Compress them for faster ticket processing and reduced storage.",
    "Zendesk limits attachments to 50 MB per ticket. Compress large documents to speed up ticket loading.",
    [{ q: "What is Zendesk's attachment limit?", a: "50 MB per attachment in tickets." }, { q: "Will agents see quality loss?", a: "At moderate compression, documents remain fully legible." }]),

  v("compress-pdf-for-asana", "Compress PDF for Asana", "Asana",
    "Compress PDF for Asana — Reduce Task Attachment Size",
    "Shrink PDFs for Asana task and project attachments. Free tool.",
    ["compress pdf asana", "asana pdf attachment", "reduce pdf asana task", "shrink pdf project management"],
    categories.platform,
    "Asana tasks with large PDF attachments load slowly. Compress files for better team collaboration.",
    "Asana Premium and Business allow 100 MB per attachment. Starter is limited.",
    [{ q: "What is Asana's file limit?", a: "Starter: 100 MB per task. Premium/Business: 100 MB per task." }, { q: "Does compression help team workflows?", a: "Yes. Smaller files mean faster loading for everyone on the team." }]),
];

// ── Export category list for index page ───────────────────────────────────
export const variantCategories = Object.entries(categories).map(([key, label]) => ({
  key,
  label,
  variants: seoVariants.filter((v) => v.category === label),
}));
